"""SVG rendering utilities for the GitHub profile engine."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import timezone
from html import escape

from generator.config import Theme
from generator.streak_generator import StreakMetrics


@dataclass(frozen=True)
class MetricBox:
    """A single dashboard metric displayed in an SVG card."""

    label: str
    value: str
    x: int
    y: int
    width: int
    accent: str


class SvgRenderer:
    """Render profile SVG assets using a shared visual system."""

    def __init__(self, theme: Theme) -> None:
        self.theme = theme

    def render_streak(self, metrics: StreakMetrics) -> str:
        """Render the custom GitHub streak card."""

        last_updated = metrics.last_updated.astimezone(timezone.utc).strftime(
            "%b %d %H:%M UTC"
        )
        boxes = [
            MetricBox(
                "Current Streak",
                f"{metrics.current_streak} days",
                64,
                152,
                190,
                self.theme.primary,
            ),
            MetricBox(
                "Longest Streak",
                f"{metrics.longest_streak} days",
                270,
                152,
                190,
                self.theme.secondary,
            ),
            MetricBox(
                "Total Contributions",
                f"{metrics.total_contributions:,}",
                476,
                152,
                220,
                self.theme.accent,
            ),
            MetricBox(
                "Contributions Today",
                f"{metrics.contributions_today:,}",
                712,
                152,
                210,
                self.theme.primary,
            ),
            MetricBox(
                "Last Updated",
                last_updated,
                938,
                152,
                198,
                self.theme.secondary,
            ),
        ]

        return self._document(
            width=1200,
            height=300,
            body=f"""
  <defs>
    {self._shared_defs()}
    <filter id="softGlow" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="4" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <rect width="1200" height="300" rx="28" fill="{self.theme.background}"/>
  <rect x="1.5" y="1.5" width="1197" height="297" rx="26.5"
        fill="none" stroke="url(#borderGradient)" stroke-width="3"
        filter="url(#softGlow)" opacity="0.88"/>
  {self._grid(1200, 300)}
  <path d="M48 108 H396 C436 108 436 80 476 80 H676 C716 80 716 108 756 108 H1152"
        fill="none" stroke="url(#borderGradient)" stroke-width="3"
        stroke-linecap="round" opacity="0.64">
    <animate attributeName="stroke-dasharray" values="12 18;22 12;12 18"
             dur="6s" repeatCount="indefinite"/>
  </path>
  <circle cx="48" cy="108" r="5" fill="{self.theme.primary}">
    <animate attributeName="opacity" values="0.35;1;0.35" dur="3s"
             repeatCount="indefinite"/>
  </circle>
  <circle cx="676" cy="80" r="5" fill="{self.theme.accent}">
    <animate attributeName="r" values="5;8;5" dur="4s" repeatCount="indefinite"/>
  </circle>
  <circle cx="1152" cy="108" r="5" fill="{self.theme.secondary}">
    <animate attributeName="opacity" values="1;0.35;1" dur="3s"
             repeatCount="indefinite"/>
  </circle>
  <text x="64" y="62" font-family="Segoe UI, Arial, sans-serif"
        font-size="30" font-weight="700" fill="{self.theme.text}">🔥 GITHUB STREAK</text>
  <text x="66" y="93" font-family="Segoe UI, Arial, sans-serif"
        font-size="16" fill="{self.theme.muted}">Consistency Builds Excellence</text>
  <text x="1006" y="66" text-anchor="end"
        font-family="Segoe UI, Arial, sans-serif" font-size="14"
        fill="{self.theme.muted}">@{escape(metrics.username)}</text>
  <text x="1136" y="66" text-anchor="end"
        font-family="Segoe UI, Arial, sans-serif" font-size="14"
        fill="{self.theme.secondary}">{escape(metrics.display_name)}</text>
  {''.join(self._metric_box(box) for box in boxes)}
  <path d="M64 260 H1136" stroke="url(#borderGradient)" stroke-width="2"
        stroke-linecap="round" opacity="0.7"/>
  <text x="64" y="279" font-family="Segoe UI, Arial, sans-serif"
        font-size="12" fill="{self.theme.muted}">
    Powered by GitHub GraphQL API • Generated by GitHub Actions
  </text>
""",
        )

    def render_analytics_placeholder(self, metrics: StreakMetrics) -> str:
        """Render a lightweight analytics card for the initial engine."""

        return self._document(
            width=1200,
            height=260,
            body=f"""
  <defs>{self._shared_defs()}</defs>
  <rect width="1200" height="260" rx="24" fill="{self.theme.background}"/>
  <rect x="1.5" y="1.5" width="1197" height="257" rx="22.5"
        fill="none" stroke="url(#borderGradient)" stroke-width="3" opacity="0.82"/>
  {self._grid(1200, 260)}
  <text x="64" y="72" font-family="Segoe UI, Arial, sans-serif"
        font-size="28" font-weight="700" fill="{self.theme.text}">GITHUB ANALYTICS</text>
  <text x="66" y="104" font-family="Segoe UI, Arial, sans-serif"
        font-size="16" fill="{self.theme.muted}">Contribution intelligence for @{escape(metrics.username)}</text>
  <text x="64" y="170" font-family="Segoe UI, Arial, sans-serif"
        font-size="54" font-weight="700" fill="{self.theme.primary}">{metrics.total_contributions:,}</text>
  <text x="66" y="202" font-family="Segoe UI, Arial, sans-serif"
        font-size="16" fill="{self.theme.muted}">contributions in the tracked window</text>
  <path d="M520 190 C640 90 760 220 900 120 S1070 110 1136 72"
        fill="none" stroke="url(#borderGradient)" stroke-width="5"
        stroke-linecap="round">
    <animate attributeName="opacity" values="0.55;1;0.55" dur="5s"
             repeatCount="indefinite"/>
  </path>
""",
        )

    def render_divider(self) -> str:
        """Render a compact animated divider."""

        return self._document(
            width=1200,
            height=80,
            body=f"""
  <defs>{self._shared_defs()}</defs>
  <rect width="1200" height="80" fill="{self.theme.background}"/>
  <path d="M60 40 H1140" stroke="url(#borderGradient)" stroke-width="3"
        stroke-linecap="round"/>
  <circle cx="600" cy="40" r="8" fill="{self.theme.primary}">
    <animate attributeName="r" values="8;13;8" dur="3s" repeatCount="indefinite"/>
  </circle>
""",
        )

    def render_footer(self) -> str:
        """Render the local footer SVG displayed by README."""

        return self._document(
            width=1200,
            height=140,
            body=f"""
  <defs>{self._shared_defs()}</defs>
  <rect width="1200" height="140" fill="{self.theme.background}"/>
  <path d="M0 96 C220 42 360 142 560 86 S900 42 1200 92 V140 H0 Z"
        fill="{self.theme.accent}" opacity="0.24"/>
  <path d="M0 104 C240 50 410 132 610 78 S940 58 1200 102"
        fill="none" stroke="{self.theme.primary}" stroke-width="3" opacity="0.82"/>
  <text x="600" y="54" text-anchor="middle"
        font-family="Segoe UI, Arial, sans-serif" font-size="22"
        font-weight="700" fill="{self.theme.text}">Made with GitHub Actions by Onkar Jadhav</text>
  <text x="600" y="82" text-anchor="middle"
        font-family="Segoe UI, Arial, sans-serif" font-size="14"
        fill="{self.theme.muted}">Learning today. Building tomorrow.</text>
""",
        )

    def _metric_box(self, box: MetricBox) -> str:
        value_size = 19 if len(box.value) > 14 else 30
        return f"""
  <g>
    <rect x="{box.x}" y="{box.y}" width="{box.width}" height="82" rx="16"
          fill="{self.theme.background}" stroke="{box.accent}" stroke-width="1.5"
          opacity="0.96"/>
    <rect x="{box.x}" y="{box.y}" width="{box.width}" height="82" rx="16"
          fill="{box.accent}" opacity="0.06"/>
    <text x="{box.x + 20}" y="{box.y + 30}" font-family="Segoe UI, Arial, sans-serif"
          font-size="13" fill="{self.theme.muted}">{escape(box.label)}</text>
    <text x="{box.x + 20}" y="{box.y + 62}" font-family="Segoe UI, Arial, sans-serif"
          font-size="{value_size}" font-weight="700" fill="{self.theme.text}">{escape(box.value)}</text>
  </g>
"""

    def _shared_defs(self) -> str:
        return f"""
    <linearGradient id="borderGradient" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="{self.theme.primary}"/>
      <stop offset="52%" stop-color="{self.theme.secondary}"/>
      <stop offset="100%" stop-color="{self.theme.accent}"/>
    </linearGradient>
"""

    def _grid(self, width: int, height: int) -> str:
        vertical = "\n".join(
            f'    <path d="M{x} 0 V{height}"/>' for x in range(80, width, 80)
        )
        horizontal = "\n".join(
            f'    <path d="M0 {y} H{width}"/>' for y in range(40, height, 40)
        )
        return f"""
  <g opacity="0.08" stroke="{self.theme.muted}" stroke-width="1">
{horizontal}
{vertical}
  </g>
"""

    @staticmethod
    def _document(width: int, height: int, body: str) -> str:
        return (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
            f'height="{height}" viewBox="0 0 {width} {height}" '
            'role="img" aria-labelledby="title desc">\n'
            "  <title id=\"title\">Onkar Jadhav GitHub Profile Asset</title>\n"
            "  <desc id=\"desc\">Generated SVG asset for the onkar0629 GitHub profile.</desc>\n"
            f"{body}\n"
            "</svg>\n"
        )
